# A sample Gemfile
source "https://rubygems.org"

gem 'radar-api', require: 'radar-api', git: 'https://bitbucket.org/investtools/radar-api.git'
gem 'thin'
gem 'i18n'
gem 'active_support'
gem 'radar-app', git: 'https://bitbucket.org/investtools/radar-app.git'

group :test do
  gem 'rspec'
end

